# Generated by Django 3.0.6 on 2020-05-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0007_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
