# Generated by Django 3.0.6 on 2020-06-04 15:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapping", "0010_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="rating", field=models.FloatField(default=0),
        ),
    ]
